modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="syndred"
version="1.0.0"
displayName="Syndred"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="The Syndred Team"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "syndred.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.syndred]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.syndred]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.syndred]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration